repos:
  # applies removal of trailing spaces and other small fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: '\.(py|txt)$' # Only run on .py and .txt files
      - id: end-of-file-fixer
        files: '\.(py|txt)$'
  # suggests linting and formatting fixes
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
        - id: ruff-check
          args: [--line-length, '120', --fix]
        - id: ruff-format
          args: [--line-length, '120']
  # suggests spelling corrections
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
        - id: codespell
        # don't suggest correcting 'slac' to 'slack'
          args: ["--check-hidden", "-L", "slac"]
