apiVersion: v1
kind: Pod
metadata:
  name: rf-phase-anomaly-detection-pod
  labels:
    app: rf-phase-anomaly-detection-pod
spec:
  containers:
  - name: rf-phase-anomaly-detection-pod
    image: scr.svc.stanford.edu/smiskov/rf-phase-anomaly-detection:0.2
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]