---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rf-phase-anomaly-detection-deployment
  namespace: rf-phase-anomaly-detection
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: rf-phase-anomaly-detection
  template:
    metadata:
      labels:
        app: rf-phase-anomaly-detection
    spec:
      securityContext:
        fsGroup: 3757
      containers:
      - name: rf-phase-anomaly-detection
        image: ghcr.io/slaclab/rf-phase-anomaly-detection:latest
        command: ['python', '-m', 'main', '-dsl', '-ll', '20']  # run without stdout logging, log at info level
        imagePullPolicy: Always
        restartPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "5"
          limits:
            memory: "2Gi"
            cpu: "8"
        env:
          - name: K2EG_PYTHON_CONFIGURATION_PATH_FOLDER
            value: /app/config
          - name: TZ
            value: "America/Los_Angeles"
        envFrom:
          - configMapRef:
              name: epics-gateway-config
        volumeMounts:
          - name: s3cmd-config-volume
            mountPath: /app/config/k2eg.ini
            subPath: k2eg.ini
          - name: sdf-storage
            mountPath: /app/saved_candidates
            subPath: store/bsas/nc_CoAD/saved_candidates
          - name: sdf-storage
            mountPath: /app/logs
            subPath: store/bsas/nc_CoAD/server_logs
      volumes:
        - name: s3cmd-config-volume
          configMap:
            name: k2eg-config-map
        - name: sdf-storage
          persistentVolumeClaim:
            claimName: sdf-data-storage

---
# apparently, this points to /sdf/data/ad/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdf-data-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: sdf-data-ad
